// <auto-generated />
using System;
using EFCoreCodeFirstBogusSeedingDemo.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreCodeFirstBogusSeedingDemo.Migrations
{
    [DbContext(typeof(DemoDBContext))]
    [Migration("20240226123624_TestMigration")]
    partial class TestMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFCoreCodeFirstBogusSeedingDemo.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suburb")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("Addressess");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5609d80-1aa1-9454-9846-2c4ee0c9749b"),
                            Country = "Falkland Islands (Malvinas)",
                            HouseNumber = "99465",
                            IsDeleted = false,
                            PersonId = new Guid("86be9f18-14a9-2172-2063-de168d905f72"),
                            Province = "Alabama",
                            Suburb = "Predovicmouth"
                        },
                        new
                        {
                            Id = new Guid("e3e3ff97-23e1-aa86-8ca9-a70806611ee0"),
                            Country = "Gibraltar",
                            HouseNumber = "9015",
                            IsDeleted = false,
                            PersonId = new Guid("45dad974-2b4d-c26f-a6c3-6c0ebc31c3e3"),
                            PostalCode = "51728",
                            Province = "Mississippi",
                            Street = "Satterfield Drive"
                        },
                        new
                        {
                            Id = new Guid("81d90631-7565-9016-4ddb-87d4729571a7"),
                            Country = "Bahrain",
                            HouseNumber = "202",
                            IsDeleted = false,
                            PersonId = new Guid("249819db-3c54-6d1f-00fd-a72d62fb3422"),
                            PostalCode = "17434",
                            Province = "New Hampshire",
                            Street = "Carolyn Skyway",
                            Suburb = "West Vernershire"
                        },
                        new
                        {
                            Id = new Guid("9f4c944e-7a57-e41b-038a-83ed06bece81"),
                            Country = "Switzerland",
                            HouseNumber = "9991",
                            IsDeleted = false,
                            PersonId = new Guid("c80201d5-18d9-6549-6074-d1f25030273a"),
                            PostalCode = "35150-4248",
                            Province = "West Virginia",
                            Street = "Braun Ramp",
                            Suburb = "Lake Nathaniel"
                        },
                        new
                        {
                            Id = new Guid("510c5782-5b43-14e8-52b9-b7c6e78a964c"),
                            Country = "Cuba",
                            IsDeleted = false,
                            PersonId = new Guid("8e1d5c9e-f6b0-00f1-d05d-ac374b014d4c"),
                            PostalCode = "43610",
                            Province = "Alaska",
                            Street = "Nicolas Landing",
                            Suburb = "Nikkoside"
                        },
                        new
                        {
                            Id = new Guid("1973214f-2304-e920-1820-4b283810918e"),
                            Country = "Sweden",
                            IsDeleted = false,
                            PersonId = new Guid("271c07b4-9e29-23cc-d0d7-201ffdb5b823"),
                            PostalCode = "47546-2747",
                            Province = "Wisconsin"
                        },
                        new
                        {
                            Id = new Guid("53c98e15-ce14-cd23-4a01-ec1e02c07e4d"),
                            Country = "Martinique",
                            HouseNumber = "9006",
                            IsDeleted = false,
                            PersonId = new Guid("dc9e9f52-a627-d5a7-10e2-0046e72830d4"),
                            PostalCode = "83879",
                            Province = "Alaska",
                            Street = "Mueller Cove",
                            Suburb = "East Melissa"
                        },
                        new
                        {
                            Id = new Guid("bc69e0bc-c69e-b701-4886-741dfda4fdbf"),
                            Country = "Somalia",
                            HouseNumber = "5205",
                            IsDeleted = false,
                            PersonId = new Guid("f8b44a4d-8a3a-f77b-1bb6-c06fc235670a"),
                            PostalCode = "92147-0114",
                            Province = "Montana",
                            Street = "Dooley Drives",
                            Suburb = "Cheyenneview"
                        },
                        new
                        {
                            Id = new Guid("34ef5ad7-21ad-ccb5-07a9-9bcd731c6a7e"),
                            Country = "Argentina",
                            HouseNumber = "883",
                            IsDeleted = false,
                            PersonId = new Guid("1d4ae7c8-e92e-300f-b259-40487b719964"),
                            PostalCode = "57776",
                            Province = "New Jersey",
                            Street = "Rudolph Route",
                            Suburb = "Port Sidville"
                        },
                        new
                        {
                            Id = new Guid("6957d7de-35b7-3028-1715-0a1b92ecf517"),
                            Country = "Andorra",
                            HouseNumber = "63880",
                            IsDeleted = false,
                            PersonId = new Guid("912e6e43-7ec6-052b-9dd0-f88ede967de8"),
                            PostalCode = "98479-5981",
                            Province = "Hawaii",
                            Street = "Harold View",
                            Suburb = "Westonberg"
                        });
                });

            modelBuilder.Entity("EFCoreCodeFirstBogusSeedingDemo.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86be9f18-14a9-2172-2063-de168d905f72"),
                            ContactNumber = "0373167737",
                            Email = "Jeff_Lemke@yahoo.com",
                            FirstName = "Jeff",
                            IsDeleted = false,
                            LastName = "Lemke"
                        },
                        new
                        {
                            Id = new Guid("45dad974-2b4d-c26f-a6c3-6c0ebc31c3e3"),
                            ContactNumber = "0559451688",
                            Email = "Myrtle_Runolfsson@hotmail.com",
                            FirstName = "Myrtle",
                            IsDeleted = false,
                            LastName = "Runolfsson"
                        },
                        new
                        {
                            Id = new Guid("249819db-3c54-6d1f-00fd-a72d62fb3422"),
                            ContactNumber = "0376375104",
                            Email = "Myrtle.Hudson16@yahoo.com",
                            FirstName = "Myrtle",
                            IsDeleted = false,
                            LastName = "Hudson"
                        },
                        new
                        {
                            Id = new Guid("c80201d5-18d9-6549-6074-d1f25030273a"),
                            ContactNumber = "0729739345",
                            Email = "Irene.Harris@yahoo.com",
                            FirstName = "Irene",
                            IsDeleted = false,
                            LastName = "Harris"
                        },
                        new
                        {
                            Id = new Guid("8e1d5c9e-f6b0-00f1-d05d-ac374b014d4c"),
                            ContactNumber = "0110591873",
                            Email = "Glenn11@yahoo.com",
                            FirstName = "Glenn",
                            IsDeleted = false,
                            LastName = "Schiller"
                        },
                        new
                        {
                            Id = new Guid("271c07b4-9e29-23cc-d0d7-201ffdb5b823"),
                            ContactNumber = "0940632890",
                            Email = "Greg.Frami@gmail.com",
                            FirstName = "Greg",
                            IsDeleted = false,
                            LastName = "Frami"
                        },
                        new
                        {
                            Id = new Guid("dc9e9f52-a627-d5a7-10e2-0046e72830d4"),
                            ContactNumber = "0476225643",
                            Email = "Judy.Kihn88@yahoo.com",
                            FirstName = "Judy",
                            IsDeleted = false,
                            LastName = "Kihn"
                        },
                        new
                        {
                            Id = new Guid("f8b44a4d-8a3a-f77b-1bb6-c06fc235670a"),
                            ContactNumber = "0225566141",
                            Email = "Frederick.Daugherty60@gmail.com",
                            FirstName = "Frederick",
                            IsDeleted = false,
                            LastName = "Daugherty"
                        },
                        new
                        {
                            Id = new Guid("1d4ae7c8-e92e-300f-b259-40487b719964"),
                            ContactNumber = "0134523521",
                            Email = "Janice_Homenick28@gmail.com",
                            FirstName = "Janice",
                            IsDeleted = false,
                            LastName = "Homenick"
                        },
                        new
                        {
                            Id = new Guid("912e6e43-7ec6-052b-9dd0-f88ede967de8"),
                            ContactNumber = "0050937983",
                            Email = "Perry59@gmail.com",
                            FirstName = "Perry",
                            IsDeleted = false,
                            LastName = "Wiegand"
                        });
                });

            modelBuilder.Entity("EFCoreCodeFirstBogusSeedingDemo.Entities.Address", b =>
                {
                    b.HasOne("EFCoreCodeFirstBogusSeedingDemo.Entities.Person", "Person")
                        .WithOne("Address")
                        .HasForeignKey("EFCoreCodeFirstBogusSeedingDemo.Entities.Address", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EFCoreCodeFirstBogusSeedingDemo.Entities.Person", b =>
                {
                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
